# Generated by Django 3.1.2 on 2020-10-16 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models.session_day
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameterset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=1)),
                ('number_of_players', models.IntegerField(default=1)),
                ('heart_activity_inital', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('heart_parameter_1', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('heart_parameter_2', models.DecimalField(decimal_places=10, default=3, max_digits=20)),
                ('heart_parameter_3', models.DecimalField(decimal_places=10, default=60, max_digits=20)),
                ('immune_activity_inital', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('immune_parameter_1', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('immune_parameter_2', models.DecimalField(decimal_places=10, default=3, max_digits=20)),
                ('immune_parameter_3', models.DecimalField(decimal_places=10, default=60, max_digits=20)),
                ('treatment_pay_1', models.DecimalField(decimal_places=2, default=4.0, max_digits=6)),
                ('treatment_pay_2', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('treatment_pay_3', models.DecimalField(decimal_places=2, default=16.0, max_digits=6)),
                ('treatment_3_heart_bonus', models.DecimalField(decimal_places=2, default=16.0, max_digits=6)),
                ('treatment_3_immune_bonus', models.DecimalField(decimal_places=2, default=16.0, max_digits=6)),
                ('treatment_3_bonus_target_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experiment Parameter Set',
                'verbose_name_plural': 'Experiment Parameter Sets',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameterset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Experiment Session',
                'verbose_name_plural': 'Experiment Sessions',
            },
        ),
        migrations.CreateModel(
            name='Session_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Login Key')),
                ('name', models.CharField(max_length=300, verbose_name='Subject Name')),
                ('contact_email', models.CharField(max_length=300, verbose_name='Subject Email')),
                ('student_id', models.CharField(max_length=300, verbose_name='Student ID Number')),
                ('gmail_address', models.CharField(max_length=300, verbose_name='Gmail Address')),
                ('gmail_password', models.CharField(max_length=300, verbose_name='Gmail Password')),
                ('fitBitAccessToken', models.CharField(default='', max_length=200)),
                ('fitBitRefreshToken', models.CharField(default='', max_length=200)),
                ('fitBitUserId', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
            options={
                'verbose_name': 'Session Subject',
                'verbose_name_plural': 'Session Subjects',
            },
        ),
        migrations.CreateModel(
            name='Session_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(choices=[('one', 'Individual'), ('two', 'Individual with chat'), ('three', 'Individual with chat and bonus')], default=main.models.session_day.Treatment['one'], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
            options={
                'verbose_name': 'Session Day',
                'verbose_name_plural': 'Session Dat',
            },
        ),
    ]
