# Generated by Django 3.1.2 on 2020-10-16 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session_day_user_actvity'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
