# Generated by Django 3.1.2 on 2020-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_session_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='treatment_1_day_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='treatment_2_day_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='treatment_3_day_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(default='*** New Session ***', max_length=300),
        ),
    ]
