# Generated by Django 3.1.2 on 2020-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201016_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='softDelete',
            field=models.BooleanField(default=False),
        ),
    ]
