# Generated by Django 3.1.2 on 2020-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201016_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject',
            name='softDelete',
            field=models.BooleanField(default=False),
        ),
    ]
