# Generated by Django 3.1.2 on 2020-10-16 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_session_subject_softdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day',
            name='period_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session_day',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='session_day',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_SD'),
        ),
    ]
