# Generated by Django 3.1.2 on 2020-10-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201016_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_day_user_actvity',
            new_name='Session_day_subject_actvity',
        ),
    ]
