# Generated by Django 3.1.2 on 2020-10-17 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201016_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_subjects', to='main.session'),
        ),
    ]
