# Generated by Django 3.1.2 on 2020-10-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201017_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_days', to='main.session'),
        ),
    ]
