# Generated by Django 3.1.2 on 2020-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201018_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject',
            name='contact_email',
            field=models.CharField(default='Subject Email', max_length=300, verbose_name='Subject Email'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitAccessToken',
            field=models.CharField(default='', max_length=200, verbose_name='FitBit Access Token'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitRefreshToken',
            field=models.CharField(default='', max_length=200, verbose_name='FitBit Refresh Token'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitUserId',
            field=models.CharField(default='', max_length=200, verbose_name='FitBit User ID'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='gmail_address',
            field=models.CharField(default='Gmail Address', max_length=300, verbose_name='Gmail Address'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='gmail_password',
            field=models.CharField(default='Gmail Password', max_length=300, verbose_name='Gmail Password'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='name',
            field=models.CharField(default='Subject Name', max_length=300, verbose_name='Subject Name'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='student_id',
            field=models.CharField(default='Student ID Number', max_length=300, verbose_name='Student ID Number'),
        ),
    ]
