# Generated by Django 3.1.2 on 2020-10-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201018_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='softDelete',
            new_name='soft_delete',
        ),
        migrations.RenameField(
            model_name='session_subject',
            old_name='softDelete',
            new_name='soft_delete',
        ),
    ]
