# Generated by Django 3.1.2 on 2020-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='maxDailyEarnings',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
