# Generated by Django 3.1.2 on 2020-10-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_parameterset_number_of_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='number_of_days',
        ),
    ]
