# Generated by Django 3.1.2 on 2020-10-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_parameterset_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitAccessToken',
            field=models.CharField(default='', max_length=1000, verbose_name='FitBit Access Token'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitRefreshToken',
            field=models.CharField(default='', max_length=1000, verbose_name='FitBit Refresh Token'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitUserId',
            field=models.CharField(default='', max_length=100, verbose_name='FitBit User ID'),
        ),
    ]
