# Generated by Django 3.1.2 on 2020-10-21 22:11

from django.db import migrations, models
import main.models.session


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201021_2145'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='session',
        #     name='treatment',
        #     field=models.CharField(choices=[('one', 'Individual'), ('two', 'Individual with chat'), ('three', 'Individual with chat and bonus')], default=main.models.session.Treatment['one'], max_length=100),
        # ),
    ]
