# Generated by Django 3.1.2 on 2020-10-21 23:04

from django.db import migrations, models
import main.models.session


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_session_treatment'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='session',
        #     name='treatment',
        #     field=models.CharField(choices=[('Individual', 'one'), ('Individual with chat', 'two'), ('Individual with chat and bonus', 'three')], default=main.models.session.Treatment['one'], max_length=100),
        # ),
    ]
