# Generated by Django 3.1.2 on 2020-10-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201021_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='treatment',
            field=models.CharField(choices=[('Individual', 'One'), ('Individual with chat', 'Two'), ('Individual with chat and bonus', 'Three')], default='Individual', max_length=100),
        ),
    ]
