# Generated by Django 3.1.2 on 2020-10-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201021_2325'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='session',
        #     name='treatment',
        #     field=models.CharField(choices=[('I', 'Individual'), ('IwC', 'Individual with chat'), ('IwCpB', 'Individual with chat and bonus')], default='I', max_length=100),
        # ),
    ]
