# Generated by Django 3.1.2 on 2020-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201022_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session_day_subject_actvity',
            options={'verbose_name': 'Session Day', 'verbose_name_plural': 'Session Days'},
        ),
        migrations.AddConstraint(
            model_name='session_day_subject_actvity',
            constraint=models.UniqueConstraint(fields=('session_day', 'session_subject'), name='unique_SDSA'),
        ),
    ]
