# Generated by Django 3.1.2 on 2020-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201023_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session_day',
            options={'verbose_name': 'Session Day', 'verbose_name_plural': 'Session Days'},
        ),
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='paypal_today',
            field=models.BooleanField(default=False),
        ),
    ]
