# Generated by Django 3.1.2 on 2020-10-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201023_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='session_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session_day_subject_actvities', to='main.session_subject'),
        ),
    ]
