# Generated by Django 3.1.2 on 2020-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201024_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='heart_maintenance_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='immune_maintenance_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
