# Generated by Django 3.1.2 on 2020-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201026_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='immune_maintenance_minutes',
            field=models.IntegerField(default=480),
        ),
    ]
