# Generated by Django 3.1.2 on 2020-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201026_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='x_max_heart',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='x_max_immune',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='x_min_heart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='x_min_immune',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='x_ticks_heart',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='x_ticks_immune',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_max_heart',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=4),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_max_immune',
            field=models.DecimalField(decimal_places=2, default=0.65, max_digits=4),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_min_heart',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_min_immune',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=4),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_ticks_heart',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='y_ticks_immune',
            field=models.IntegerField(default=11),
        ),
    ]
