# Generated by Django 3.1.2 on 2020-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201028_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='immune_parameter_3',
            field=models.DecimalField(decimal_places=10, default=960, max_digits=20),
        ),
    ]
