# Generated by Django 3.1.2 on 2020-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201029_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='heart_activity_inital',
            field=models.DecimalField(decimal_places=10, default=0.75, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='immune_activity_inital',
            field=models.DecimalField(decimal_places=10, default=0.75, max_digits=20),
        ),
    ]
