# Generated by Django 3.1.2 on 2020-10-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201031_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
