# Generated by Django 3.1.2 on 2020-11-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20201102_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='invitationTextSubject',
            new_name='invitation_text_subject',
        ),
    ]
