# Generated by Django 3.1.2 on 2020-11-03 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20201102_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
