# Generated by Django 3.1.2 on 2020-11-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201103_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='heart_maintenance_minutes',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='immune_maintenance_minutes',
        ),
    ]
