# Generated by Django 3.1.2 on 2020-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20201103_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='y_max_heart',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_max_immune',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_min_heart',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_min_immune',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_ticks_heart',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_ticks_immune',
            field=models.IntegerField(default=10),
        ),
    ]
