# Generated by Django 3.1.2 on 2020-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20201103_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='x_ticks_immune',
            field=models.IntegerField(default=13),
        ),
    ]
