# Generated by Django 3.1.2 on 2020-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201103_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='fixed_pay_per_day',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=6),
        ),
    ]
