# Generated by Django 3.1.2 on 2020-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_parameterset_fixed_pay_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='x_max_heart',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='x_max_immune',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='x_ticks_heart',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='x_ticks_immune',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_max_heart',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_max_immune',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_min_heart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='y_min_immune',
            field=models.IntegerField(default=0),
        ),
    ]
