# Generated by Django 3.1.2 on 2020-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201104_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='trackerDataOnly',
            field=models.BooleanField(default=True),
        ),
    ]
