# Generated by Django 3.1.2 on 2020-11-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20201107_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_subject',
            name='consent_form',
        ),
        migrations.AddField(
            model_name='session_subject',
            name='consent_required',
            field=models.BooleanField(default=True),
        ),
    ]
