# Generated by Django 3.1.2 on 2020-11-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20201109_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='exercise_explanation',
            field=models.CharField(default='', max_length=10000, verbose_name='Exercise Explanation'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='exercise_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Exercise Hours'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='exercise_importance',
            field=models.CharField(choices=[('1', 'Very Unimportant'), ('2', 'Unimportant'), ('3', 'Somewhat Unimportant'), ('4', 'Neutral'), ('5', 'Somewhat Important'), ('6', 'Important'), ('7', 'Very Important')], default=1, max_length=100, verbose_name='Exercise Likert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='exercise_variation',
            field=models.CharField(choices=[('1', 'Very High'), ('2', 'High'), ('3', 'Somewhat High'), ('4', 'Average'), ('5', 'Somewhat Low'), ('6', 'Low'), ('7', 'Very Low')], default=1, max_length=100, verbose_name='Exercise Variation Likert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='exercise_variation_explanation',
            field=models.CharField(default='', max_length=10000, verbose_name='Exercise Variation Explanation'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='health_importance',
            field=models.CharField(choices=[('1', 'Very Unimportant'), ('2', 'Unimportant'), ('3', 'Somewhat Unimportant'), ('4', 'Neutral'), ('5', 'Somewhat Important'), ('6', 'Important'), ('7', 'Very Important')], default=1, max_length=100, verbose_name='Health Importance Likert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='health_importance_actions',
            field=models.CharField(default='', max_length=10000, verbose_name='Health Importance Actions'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='health_importance_explanation',
            field=models.CharField(default='', max_length=10000, verbose_name='Health Importance Explanation'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='health_satisfaction',
            field=models.CharField(choices=[('1', 'Very Unsatisfied'), ('2', 'Unsatisfied'), ('3', 'Somewhat Unsatisfied'), ('4', 'Neutral'), ('5', 'Somewhat Satisfied'), ('6', 'Satisfied'), ('7', 'Very Satisfied')], default=1, max_length=100, verbose_name='Health Satisfaction Likert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='sleep_variation',
            field=models.CharField(choices=[('1', 'Very High'), ('2', 'High'), ('3', 'Somewhat High'), ('4', 'Average'), ('5', 'Somewhat Low'), ('6', 'Low'), ('7', 'Very Low')], default=1, max_length=100, verbose_name='Sleep Variation Likert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='sleep_variation_explanation',
            field=models.CharField(default='', max_length=10000, verbose_name='Sleep Variation Explanation'),
        ),
    ]
