# Generated by Django 3.1.2 on 2020-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20201110_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='exercise_minutes',
            field=models.IntegerField(default=0, verbose_name='Exercise Minutes'),
        ),
    ]
