# Generated by Django 3.1.2 on 2020-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20201110_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='exercise_importance',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'Very Unimportant'), ('2', 'Unimportant'), ('3', 'Somewhat Unimportant'), ('4', 'Neutral'), ('5', 'Somewhat Important'), ('6', 'Important'), ('7', 'Very Important')], max_length=100, verbose_name='Exercise Likert'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='exercise_variation',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'No two days are the same'), ('2', 'Very much variation'), ('3', 'Much variation'), ('4', 'Average amount of variation'), ('5', 'Little variation'), ('6', 'Very little variation'), ('7', 'No variation')], max_length=100, verbose_name='Exercise Variation Likert'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='health_importance',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'Very Unimportant'), ('2', 'Unimportant'), ('3', 'Somewhat Unimportant'), ('4', 'Neutral'), ('5', 'Somewhat Important'), ('6', 'Important'), ('7', 'Very Important')], max_length=100, verbose_name='Health Importance Likert'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='health_satisfaction',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'Very Unsatisfied'), ('2', 'Unsatisfied'), ('3', 'Somewhat Unsatisfied'), ('4', 'Neutral'), ('5', 'Somewhat Satisfied'), ('6', 'Satisfied'), ('7', 'Very Satisfied')], max_length=100, verbose_name='Health Satisfaction Likert'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='sleep_importance',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'Very Unimportant'), ('2', 'Unimportant'), ('3', 'Somewhat Unimportant'), ('4', 'Neutral'), ('5', 'Somewhat Important'), ('6', 'Important'), ('7', 'Very Important')], max_length=100, verbose_name='Sleep Likert'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire1',
            name='sleep_variation',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'No two nights are the same'), ('2', 'Very much variation'), ('3', 'Much variation'), ('4', 'Average amount of variation'), ('5', 'Little variation'), ('6', 'Very little variation'), ('7', 'No variation')], max_length=100, verbose_name='Sleep Variation Likert'),
        ),
    ]
