# Generated by Django 3.1.2 on 2020-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20201110_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject',
            name='consent_signature',
            field=models.CharField(default='', max_length=300, verbose_name='Consent Signature'),
        ),
    ]
