# Generated by Django 3.1.2 on 2020-11-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_session_subject_consent_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_subject_questionnaire2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_changed', models.BooleanField(default=False, verbose_name='Sleep Changed')),
                ('sleep_changed_explaination', models.CharField(default='', max_length=10000, verbose_name='Sleep Changed Explanation')),
                ('exercise_changed', models.BooleanField(default=False, verbose_name='Exercise Changed')),
                ('exercise_changed_explaination', models.CharField(default='', max_length=10000, verbose_name='Exercise Changed Explanation')),
                ('health_concern', models.BooleanField(default=False, verbose_name='Health Concern')),
                ('health_concern_explaination', models.CharField(default='', max_length=10000, verbose_name='Health Concern Explanation')),
                ('session_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session_subject_questionnaire2', to='main.session_subject')),
            ],
            options={
                'verbose_name': 'Post Questionnaire',
                'verbose_name_plural': 'Post Questionnaires',
            },
        ),
    ]
