# Generated by Django 3.1.2 on 2020-11-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20201113_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='payment_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
