# Generated by Django 3.1.2 on 2020-11-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_session_day_subject_actvity_payment_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='session_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session_day_subject_actvities_SD', to='main.session_day'),
        ),
    ]
