# Generated by Django 3.1.2 on 2020-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20201113_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='heart_activity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='immune_activity',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
