# Generated by Django 3.1.2 on 2020-11-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20201113_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire2',
            name='health_concern',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'Very much more'), ('2', 'Much more'), ('3', 'A little more'), ('4', 'The same'), ('5', 'A little less'), ('6', 'Much less'), ('7', 'Very much less')], max_length=100, verbose_name='Health Concern Post'),
        ),
    ]
