# Generated by Django 3.1.2 on 2020-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20201113_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='heartHelpText',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='immuneHelpText',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='parameters',
            name='paymentHelpText',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
