# Generated by Django 3.1.2 on 2020-11-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20201116_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='manualHelpText',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
