# Generated by Django 3.1.2 on 2020-11-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20201118_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='blockChangeText',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='display_color',
            field=models.CharField(default='#000000', max_length=300, verbose_name='Graph Color'),
        ),
    ]
