# Generated by Django 3.1.2 on 2020-11-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20201119_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='treatment',
            field=models.CharField(choices=[('I', 'Individual'), ('IwC', 'Individual with chat'), ('IwCpB', 'Individual with chat and bonus'), ('B', 'Baseline')], default='I', max_length=100),
        ),
    ]
