# Generated by Django 3.1.2 on 2020-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20201123_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='paymentHelpTextBaseline',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
