# Generated by Django 3.1.2 on 2020-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20201123_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_minutes_fairly_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_minutes_lightly_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_minutes_sedentary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_minutes_very_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_steps',
            field=models.IntegerField(default=0),
        ),
    ]
