# Generated by Django 3.1.2 on 2020-12-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_session_day_subject_actvity_fitbit_heart_time_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='staffHomeHelpText',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
