# Generated by Django 3.1.4 on 2020-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_parameters_staffhomehelptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_city',
            field=models.CharField(default='', max_length=1000, verbose_name='Address City'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_full_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Full Name Address'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_line_1',
            field=models.CharField(default='', max_length=1000, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_line_2',
            field=models.CharField(default='', max_length=1000, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_state',
            field=models.CharField(default='', max_length=1000, verbose_name='Address State'),
        ),
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='address_zip_code',
            field=models.CharField(default='', max_length=1000, verbose_name='Address Zip Code'),
        ),
    ]
