# Generated by Django 3.1.4 on 2020-12-14 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20201214_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject',
            name='fitLastSynced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
