# Generated by Django 3.1.4 on 2020-12-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_session_subject_fitlastsynced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject',
            name='fitLastSynced',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
