# Generated by Django 3.1.4 on 2020-12-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20201214_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_subject',
            old_name='fitLastSynced',
            new_name='fitBitLastSynced',
        ),
    ]
