# Generated by Django 3.1.4 on 2020-12-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20201214_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject',
            name='fitBitTimeZone',
            field=models.CharField(default='', max_length=1000, verbose_name='FitBit Access Token'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitLastSynced',
            field=models.DateTimeField(default=None, null=True, verbose_name='FitBit Last Synced'),
        ),
    ]
