# Generated by Django 3.1.4 on 2020-12-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_auto_20201215_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_calories',
            field=models.IntegerField(default=0),
        ),
    ]
