# Generated by Django 3.1.4 on 2020-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_session_day_subject_actvity_fitbit_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='minimum_wrist_minutes',
            field=models.IntegerField(default=1080),
        ),
    ]
