# Generated by Django 3.1.4 on 2020-12-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_parameterset_minimum_wrist_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_on_wrist_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
