# Generated by Django 3.1.4 on 2020-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_session_day_subject_actvity_fitbit_on_wrist_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='heart_activity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='immune_activity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
