# Generated by Django 3.1.4 on 2020-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20201218_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject_questionnaire2',
            name='exercise_changed',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'very much more'), ('2', 'much more'), ('3', 'a little more'), ('4', 'the same'), ('5', 'a little less'), ('6', 'much less'), ('7', 'very much less')], max_length=100, verbose_name='Exercise Change Post'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire2',
            name='health_concern',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'very much more'), ('2', 'much more'), ('3', 'a little more'), ('4', 'the same'), ('5', 'a little less'), ('6', 'much less'), ('7', 'very much less')], max_length=100, verbose_name='Health Concern Post'),
        ),
        migrations.AlterField(
            model_name='session_subject_questionnaire2',
            name='sleep_changed',
            field=models.CharField(choices=[('', ''), ('0', 'N/A'), ('1', 'very much more'), ('2', 'much more'), ('3', 'a little more'), ('4', 'the same'), ('5', 'a little less'), ('6', 'much less'), ('7', 'very much less')], max_length=100, verbose_name='Sleep Change Post'),
        ),
    ]
