# Generated by Django 3.1.4 on 2020-12-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_auto_20201220_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='heart_parameter_1',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='heart_parameter_2',
            field=models.DecimalField(decimal_places=5, default=3.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='heart_parameter_3',
            field=models.DecimalField(decimal_places=5, default=6.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='immune_parameter_1',
            field=models.DecimalField(decimal_places=5, default=0.2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='immune_parameter_2',
            field=models.DecimalField(decimal_places=5, default=4.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='immune_parameter_3',
            field=models.DecimalField(decimal_places=5, default=4.0, max_digits=20),
        ),
    ]
