# Generated by Django 3.1.4 on 2021-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20201222_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent_forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Name')),
                ('body_text', models.CharField(default='', max_length=10000, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
            },
        ),
        migrations.AlterModelOptions(
            name='parameterset',
            options={'verbose_name': 'Study Parameter Set', 'verbose_name_plural': 'Study Parameter Sets'},
        ),
    ]
