# Generated by Django 3.1.4 on 2021-01-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20210110_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='consent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.consent_forms'),
        ),
    ]
