# Generated by Django 3.1.4 on 2021-01-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_parameterset_consent_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='consentForm',
        ),
    ]
