# Generated by Django 3.1.4 on 2021-01-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_remove_parameters_consentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent_forms',
            name='body_text',
            field=models.CharField(default='', max_length=50000, verbose_name='Text'),
        ),
    ]
