# Generated by Django 3.1.4 on 2021-01-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20210113_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
