# Generated by Django 3.1.4 on 2021-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_session_day_subject_actvity_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_min_heart_rate_zone_bpm',
            field=models.IntegerField(default=0),
        ),
    ]
