# Generated by Django 3.1.4 on 2021-01-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_session_day_subject_actvity_fitbit_min_heart_rate_zone_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject_questionnaire1',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
