# Generated by Django 3.1.4 on 2021-02-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_session_subject_questionnaire1_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject_questionnaire2',
            name='holiday_break_explaination',
            field=models.CharField(default='', max_length=10000, verbose_name='How did you spend your last break?'),
        ),
    ]
