# Generated by Django 3.1.4 on 2021-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_session_subject_questionnaire2_holiday_break_explaination'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_immune_time_series',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
