# Generated by Django 3.1.4 on 2021-03-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20210301_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payments_sent',
            field=models.BooleanField(default=False),
        ),
    ]
