# Generated by Django 3.1.4 on 2021-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_session_payments_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='paypalPaymentTime',
            field=models.TimeField(default='02:00'),
        ),
    ]
