# Generated by Django 3.1.4 on 2021-03-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_parameters_paypalpaymenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='paypalPaymentTime',
        ),
    ]
