# Generated by Django 3.1.4 on 2021-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20210302_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day',
            name='payments_sent',
            field=models.BooleanField(default=False),
        ),
    ]
