# Generated by Django 3.1.4 on 2021-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_remove_parameters_paypalpaymenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='payments_sent',
        ),
        migrations.AddField(
            model_name='session_day',
            name='payments_sent',
            field=models.BooleanField(default=False),
        ),
    ]
