# Generated by Django 3.1.4 on 2021-03-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20210301_2324'),
        ('main', '0101_auto_20210302_1905'),
    ]

    operations = [
    ]
