# Generated by Django 3.1.4 on 2021-03-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_merge_20210302_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='consent_required',
            field=models.BooleanField(default=True, verbose_name='Consent Form Signed'),
        ),
        migrations.AddField(
            model_name='session',
            name='questionnaire1_required',
            field=models.BooleanField(default=True, verbose_name='Pre-questionnaire Complete'),
        ),
        migrations.AddField(
            model_name='session',
            name='questionnaire2_required',
            field=models.BooleanField(default=True, verbose_name='Post-questionnaire Complete'),
        ),
        migrations.AlterField(
            model_name='session',
            name='treatment',
            field=models.CharField(choices=[('B', 'Baseline'), ('I', 'Individual'), ('ILS', 'Individual - Lump Sum'), ('IwCpB', 'Individual with chat and bonus')], default='I', max_length=100),
        ),
    ]
