# Generated by Django 3.1.4 on 2021-03-04 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20210302_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_subject',
            name='fitBitTimeZone',
            field=models.CharField(default='', max_length=1000, verbose_name='FitBit Time Zone'),
        ),
        migrations.AlterField(
            model_name='session_subject',
            name='login_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Login Key'),
        ),
    ]
