# Generated by Django 3.1.4 on 2021-03-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_auto_20210304_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_subject',
            name='gmail_address',
        ),
        migrations.RemoveField(
            model_name='session_subject',
            name='gmail_password',
        ),
    ]
