# Generated by Django 3.1.4 on 2021-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_auto_20210304_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='paypal_email_body',
            field=models.CharField(default='thanks for your participation!', max_length=200),
        ),
        migrations.AddField(
            model_name='parameters',
            name='paypal_email_subject',
            field=models.CharField(default='You have a payment from <your_org>.', max_length=200),
        ),
    ]
