# Generated by Django 3.1.4 on 2021-03-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_session_day_payments_result_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session_day',
            name='unique_SD',
        ),
        migrations.AddConstraint(
            model_name='session_day',
            constraint=models.UniqueConstraint(fields=('session', 'period_number'), name='unique_SD_period_number'),
        ),
        # migrations.AddConstraint(
        #     model_name='session_day',
        #     constraint=models.UniqueConstraint(fields=('session', 'date'), name='unique_SD_date'),
        # ),
    ]
