# Generated by Django 3.1.4 on 2021-03-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_auto_20210312_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrunctionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='*** New Session ***', max_length=300)),
            ],
            options={
                'verbose_name': 'Session Instuction Set',
                'verbose_name_plural': 'Session Instuction Sets',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.instrunctionset'),
        ),
    ]
