# Generated by Django 3.1.4 on 2021-03-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_auto_20210315_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrunctionset',
            name='title',
            field=models.CharField(default='*** Title Here ***', max_length=300),
        ),
    ]
