# Generated by Django 3.1.7 on 2021-03-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_instrunctionsetpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrunctionsetpage',
            name='instruction_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_set_pages', to='main.instrunctionset'),
        ),
    ]
