# Generated by Django 3.1.7 on 2021-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20210315_1906'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instrunctionsetpage',
            constraint=models.UniqueConstraint(fields=('instruction_set', 'time_block', 'page_type'), name='unique_instruction_page'),
        ),
    ]
