# Generated by Django 3.1.7 on 2021-03-15 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20210315_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrunctionset',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrunctionset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instrunctionsetpage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrunctionsetpage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
