# Generated by Django 3.1.7 on 2021-03-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_auto_20210315_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrunctionSet',
            new_name='InstructionSet',
        ),
        migrations.RenameModel(
            old_name='InstrunctionSetPage',
            new_name='InstructionSetPage',
        ),
        migrations.AlterModelOptions(
            name='instructionsetpage',
            options={'ordering': ['id'], 'verbose_name': 'Session Instuction Set Page', 'verbose_name_plural': 'Session Instuction Set Pages'},
        ),
    ]
