# Generated by Django 3.1.7 on 2021-03-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_auto_20210315_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='treatment',
            field=models.CharField(choices=[('Base', 'Baseline'), ('I', 'Individual'), ('A', 'Treatment A'), ('B', 'Treatment B'), ('C', 'Treatment C')], default='I', max_length=100),
        ),
    ]
