# Generated by Django 3.1.7 on 2021-03-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_auto_20210315_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionSetNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_block', models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE')], max_length=100)),
                ('notice_type', models.CharField(choices=[('ADVANCE', 'ADVANCE'), ('START', 'START')], max_length=100)),
                ('text', models.CharField(default='', max_length=50000, verbose_name='Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instruction_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_set_notices', to='main.instructionset')),
            ],
            options={
                'verbose_name': 'Session Instuction Set Notice',
                'verbose_name_plural': 'Session Instuction Set Notices',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='instructionsetnotice',
            constraint=models.UniqueConstraint(fields=('instruction_set', 'time_block', 'notice_type'), name='unique_instruction_notice'),
        ),
    ]
