# Generated by Django 3.1.7 on 2021-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_instructionsetnotice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsetnotice',
            name='text',
            field=models.CharField(default='', max_length=50000, verbose_name='Page Text'),
        ),
        migrations.AlterField(
            model_name='instructionsetnotice',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Title'),
        ),
    ]
