# Generated by Django 3.1.7 on 2021-03-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_auto_20210316_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='blockChangeSubject',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='blockChangeText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='blockPreChangeSubject',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='blockPreChangeText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='heartHelpText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='immuneHelpText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='paymentHelpText',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='paymentHelpTextBaseline',
        ),
    ]
