# Generated by Django 3.1.7 on 2021-03-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210317_0149'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session_day',
            name='unique_SD_date',
        ),
    ]
