# Generated by Django 3.1.7 on 2021-03-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_auto_20210317_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='fixed_pay_per_day',
        ),
        migrations.AddField(
            model_name='parameterset',
            name='block_1_fixed_pay_per_day',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='block_2_fixed_pay_per_day',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='block_3_fixed_pay_per_day',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6),
        ),
    ]
