# Generated by Django 3.1.7 on 2021-03-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_auto_20210325_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='treatment_3_bonus_target_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='treatment_3_heart_bonus',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='treatment_3_immune_bonus',
        ),
    ]
