# Generated by Django 3.1.7 on 2021-03-31 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_auto_20210331_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersetPaylevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parameterset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paylevels', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameterset pay level',
                'verbose_name_plural': 'Parameterset pay levels',
                'ordering': ['score'],
            },
        ),
    ]
