# Generated by Django 3.1.7 on 2021-03-31 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_parametersetpaylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetpaylevel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametersetpaylevel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
