# Generated by Django 3.1.7 on 2021-04-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_auto_20210331_2200'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parametersetpaylevel',
            constraint=models.UniqueConstraint(fields=('parameterset', 'score'), name='unique_paylevel_score'),
        ),
    ]
