# Generated by Django 3.1.7 on 2021-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_auto_20210401_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auto_pay',
            field=models.BooleanField(default=True),
        ),
    ]
