# Generated by Django 3.2.12 on 2022-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_auto_20220221_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_subject',
            name='group_number',
            field=models.IntegerField(default=1, verbose_name='Group Number'),
        ),
    ]
