# Generated by Django 3.2.12 on 2022-02-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_session_subject_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersetTimeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('immune_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fixed_pay_per_day', models.DecimalField(decimal_places=2, default=3.0, max_digits=6)),
                ('day_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameterset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeblocks', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Study Parameter Set Time Block',
                'verbose_name_plural': 'Study Parameter Set Time Blocks',
            },
        ),
    ]
