# Generated by Django 3.2.12 on 2022-02-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_parametersettimeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='block_1_day_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_1_fixed_pay_per_day',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_1_heart_pay',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_1_immune_pay',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_2_day_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_2_fixed_pay_per_day',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_2_heart_pay',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_2_immune_pay',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_3_day_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_3_fixed_pay_per_day',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_3_heart_pay',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='block_3_immune_pay',
        ),
        migrations.AlterField(
            model_name='parametersettimeblock',
            name='parameterset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='main.parameterset'),
        ),
    ]
