# Generated by Django 3.2.12 on 2022-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0134_auto_20220223_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersettimeblock',
            options={'ordering': ['block_number'], 'verbose_name': 'Study Parameter Set Time Block', 'verbose_name_plural': 'Study Parameter Set Time Blocks'},
        ),
        migrations.AddField(
            model_name='parametersettimeblock',
            name='block_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='parametersettimeblock',
            constraint=models.UniqueConstraint(fields=('block_number', 'parameterset'), name='unique_time_block'),
        ),
    ]
