# Generated by Django 3.2.12 on 2022-02-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_auto_20220223_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsetnotice',
            name='time_block',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instructionsetpage',
            name='time_block',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX')], max_length=100),
        ),
    ]
