# Generated by Django 3.2.12 on 2022-02-25 22:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_auto_20220224_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsetpage',
            name='text',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
    ]
