# Generated by Django 3.2.12 on 2022-02-25 22:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_alter_instructionsetpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionsetnotice',
            name='text',
            field=tinymce.models.HTMLField(default='', verbose_name='Page Text'),
        ),
    ]
