# Generated by Django 3.2.12 on 2022-02-25 22:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_alter_instructionsetnotice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent_forms',
            name='body_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Text'),
        ),
    ]
