# Generated by Django 3.2.12 on 2022-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_auto_20220228_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_day_subject_actvity',
            name='fitbit_height',
            field=models.IntegerField(default=0),
        ),
    ]
