# Generated by Django 3.2.12 on 2022-02-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_session_day_subject_actvity_fitbit_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='fitbit_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='session_day_subject_actvity',
            name='fitbit_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
