# Generated by Django 3.2.12 on 2022-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_auto_20220302_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session_day',
            options={'ordering': ['period_number'], 'verbose_name': 'Session Day', 'verbose_name_plural': 'Session Days'},
        ),
        migrations.AlterModelOptions(
            name='session_day_subject_actvity',
            options={'ordering': ['session_day__period_number'], 'verbose_name': 'Session Day', 'verbose_name_plural': 'Session Days'},
        ),
        migrations.AddField(
            model_name='parametersettimeblock',
            name='show_notice',
            field=models.BooleanField(default=True),
        ),
    ]
