name: ESI Fitbit Application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
    	ALLOWED_HOSTS: localhost 127.0.0.1
    	DBHOST: localhost
    	DBNAME: github_actions
    	DBPASS: postgres
    	DBUSER: postgres
    	EMAIL_HOST_PASSWORD: abc
    	EMAIL_HOST_USER: abc
    	FITBIT_AUTHORIZATION: abc
    	FITBIT_CLIENT_ID: abc
    	LOG_LOCATION: abc
    	PPMS_HOST: abc
    	PPMS_PASSWORD: abc
    	PPMS_USER_NAME: abc
    	SECRET_KEY: super_duper_secret_key

    services:
      postgres:
        image: postgres:12.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install pytest-django
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12'
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: py.test
